### ISSUE TITLE
Question : Enabling CORS

### ISSUE THREAD

**Issue by k5nn** [awesomeeng/awesome-server#2]
when trying to fetch data from awesome-server it's returning a CORS error all I have to do is specify the Access-Control-Allow-Origin in the response right?...

**Comment by arei** [comment]
CORS is more complicated than that and doing it right is always going to be your best option. That said, I will share with you a quick and dirty CORS solution I used on another project that uses AwesomeServer. 

I do encourage you to read more about CORS and implement it correctly though. I suggest starting with MDN’s article on CORS though: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Here what I did for a quick solution...

```
let server = new AwesomeServer();
server.addHTTPServer({
	hostname: config.server.hostname,
	port: process.env.PORT || config.server.port
});

// CORS support
server.route("*","*",(path,request,response)=>{
	response.setHeader("Access-Control-Allow-Origin", "http://"+config.server.hostname+":"+config.server.port);
	response.setHeader("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE");
	response.setHeader("Access-Control-Allow-Headers", "Content-Type");
});

// Send to controllers
server.route("*","/api","./controllers");

await server.start();
```
