### ISSUE TITLE
[Microsoft Edge] Error when doing a request.readJSON()

### ISSUE THREAD

**Issue by k5nn** [awesomeeng/awesome-server#3]
I was reading the docs on how to read the body of a form and stumbled upon readJSON upon trying said function I'm receiving a 

```
SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at /mnt/e/project/node_modules/@awesomeeng/awesome-server/src/AbstractRequest.js:249:29
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

error upon trying my hand a debugging I found that the bytes being parsed include if I'm not mistaken the webkit headers ( `------WebKitFormBoundary5lTCVtTzptVJRTFD\r\nContent-Disposition: form-data;` ) along with the data I want to access I could just truncate the bytes but I don't think that's the issue plus the idea of relying on the fact that they're always static doesn't sit well with me any help would be appreciated

**Comment by arei** [comment]
You are trying to read content that is formatted as either `application/x-www-form-urlencoded` or `multipart/form-data`. `request.readJSON()` will not work with data of that type, it will only work with data formatted as `application/json`.  

Your best bet will be to use `request.read()` which will return a `Promise<Buffer>` which you can parse yourself.
