### ISSUE TITLE
[ Question ] socket.io integration

### ISSUE THREAD

**Issue by k5nn** [awesomeeng/awesome-server#5]
I've been looking at socket.io docs on how to integrate primarily with these sections

https://github.com/socketio/socket.io#in-conjunction-with-express
https://github.com/socketio/socket.io#in-conjunction-with-koa

it doesn't seem like that's possible with Awesome-Server cause the addHTTPServer methods already do that the createServer and listen part the other thing I've seen is to use the server.listener in hapi

https://hapi.dev/api/?v=20.0.0#-serverlistener

so is it possible to expose the the HTTPServer object's listener?...

**Comment by arei** [comment]
AddHTTPServer() returns an AbstractServer object, from which you can obtain the original HTTPServer thusly: 

const originalServer = server.addHTTPServer().original;

Will that satisfy your need?

**Comment by k5nn** [comment]
it returns a null for me not the server instance as stated in the code I tried wrapping the server.start() in an async function and doing the .then() method cause I saw the server returns a promise but when I tried to console.log( server ) with the HTTPServer's server symbol still null though it does seem like it's doing as intended cause Awesome-Log is logging the message that the HTTPServer was started successfully

I'm doing it like this

`

    let server = new AwesomeServer();
    let socket_server = null

    const start_server = async () => {
	    await server.start().then( console.log( socket_server ) ) // symbols server and running are null and false respectively 
    }

    socket_server = server.addHTTPServer({
		    hostname: localhost,
		    port: 8000
		})

    start_server()
`

**Comment by arei** [comment]
Sorry, I misspoke...

`addHTTPServer` returns an instance of `AbstractServer`. Once the server is started (via `server.start()`) `AbstractServer has a property called `original` that will return a reference to the node HTTP server object that underlies it. You can then use that for your socket.io stuff.

Small code example:

```const AwesomeServer = require('./src/AwesomeServer');

let server = new AwesomeServer();
let http_server = server.addHTTPServer({
	hostname: 'localhost',
	port: 8000
});

(async function(){
	await server.start();
	socket_server = http_server.original;
	console.log(socket_server);	
})();
```
